spring.application.name=eurekaServer

server.port=8761

#se dice asi mismo que no se registre como un cliente
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#que preifera laip por arriba del host
eureka.instance.prefer-ip-address=true